### ISSUE TITLE
关于mooc网短信课程的困惑

### ISSUE THREAD

**Issue by sunxu3074** [hongyangAndroid/mooc_hyman#1]
洋神,我写了个购物车demo,用的tablayout.可显示时候viewpager.setAdapter中,只显示一个fragment而且还是错乱的.我明明new了3个哎,找了半天没发现答案,特来请教洋神.望告知,非常感激!!
代码地址:https://github.com/sunxu3074/ShoppingDemo/blob/master/app/src/main/java/io/github/sunxu3074/shoppoingdemo/activity/CategoryDetailsActivity.java

**Comment by hongyangAndroid** [comment]
不好意思哈，这个类我看了两遍，我也没发现有什么问题。

**Comment by sunxu3074** [comment]
好吧，麻烦洋神了~会不会fragment把上边的fragment给覆盖了~第二个tab显示的是第三个fragment，好苦恼~我找了一天的bug了

**Comment by sunxu3074** [comment]
找到bug了,我把在fragment中的getActivity().findViewById()换乘了getView()就好了~谢谢洋神了:)
